# version: '3.8' # Hoặc "3"

# services:
#   app:
#     build: .
#     ports:
#       - '5000:5000'
#     env_file:
#       - .env
#     command: /usr/local/bin/wait-for-it.sh db:3306 -- npm start
#     depends_on:
#       - db

#   db:
#     image: mysql:5.7
#     ports:
#       - '3307:3306'
#     environment:
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:

# version: '3.8' # Hoặc "3"

# services:
#   app:
#     build: .
#     ports:
#       - '5000:5000'
#     env_file:
#       - .env
#     command: /usr/local/bin/wait-for-it.sh db:3306 -- npm start
#     depends_on:
#       - db

#   db:
#     image: mysql:5.7
#     ports:
#       - '3307:3306'
#     environment:
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:

# =============================================================

version: '3'
services:
  app:
    build:
      context: ./src
    container_name: nodejs-app
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env # Thêm dòng này để sử dụng các biến từ .env
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql # Dùng tên dịch vụ MySQL làm host
      - DB_PORT=3306 # Dùng cổng nội bộ của MySQL container
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=apet123456789

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: apet123456789
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
