@urlDev=http://localhost:4000

GET {{urlDev}}/index

###
GET {{urlDev}}/pet

###
GET {{urlDev}}/post

###
GET {{urlDev}}/api/v1/blogs

###
GET {{urlDev}}/api/v1/categories/product-count

###
GET {{urlDev}}/api/v1/categories/product-count/doc

