# # Sử dụng Node.js phiên bản 20
# FROM node:20

# # Thiết lập thư mục làm việc
# WORKDIR /app

# # Copy các file package.json và package-lock.json
# COPY package*.json /app/

# # Cài đặt các package phụ thuộc
# RUN npm install

# # Copy script wait-for-it.sh để chờ MySQL sẵn sàng

# # Copy toàn bộ mã nguồn vào container
# COPY . .

# # Mở cổng 5000 cho ứng dụng Node.js
# EXPOSE 5000

# ==================================================

# Sử dụng image node phiên bản LTS
FROM node:20

# Thiết lập thư mục làm việc trong container
WORKDIR /usr/src/app

# Sao chép package.json và cài đặt dependencies
COPY ../package*.json ./
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Expose cổng mà ứng dụng sẽ chạy
EXPOSE 4000

# Chạy ứng dụng
CMD ["npm", "start"]
